# Dataset paths
path: /data/Bartscht/YOLO  # Base path
train: images/train        # Path to training images
val: images/val           # Path to validation images
test: images/test         # Path to test images

# Class configuration
nc: 7  # Number of classes

# Class names in ordered list
names:
  - Grasper
  - Bipolar
  - Hook
  - Scissors
  - Clipper
  - Irrigator
  - SpecimenBag

# Class weights
class_weights:
  0: 0.32
  1: 1.47
  2: 0.64
  3: 3.1
  4: 2.36
  5: 1.39
  6: 0.0