path: /data/Bartscht/YOLO
train: images/train
val: images/val
test: images/test
nc: 7
names:
- Grasper
- Bipolar
- Hook
- Scissors
- Clipper
- Irrigator
- SpecimenBag
class_weights:
  0: 0.32
  1: 1.47
  2: 0.64
  3: 3.1
  4: 2.36
  5: 1.39
  6: 0.0
